apiVersion: v1
kind: Pod
metadata:
  name: lab2-app2
  labels:
    name: lab2-app2
spec:
  containers:
  - name: lab2-app2
    image: stav:0.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8070